-- officers
INSERT INTO students (name,major,class,membership) VALUES
('Mason McCree', 'Information Technology', 'Sophomore', 'Officer'),
('Yonnas Alemu', 'Computer Science', 'Junior', 'Officer'),
('Ese Thaddeus', 'Computer Engineering', 'Sophomore', 'Officer'),
('Brendan Senatus', 'Cybersecurity', 'Sophomore', 'Officer'),
('Kataali Nashiru', 'Data Science', 'Junior', 'Officer'),
('Alvin Wande', 'Computer Science', 'Freshman', 'Member'),
('Miriam Afolabi', 'Pre-Med', 'Sophomore', 'Member'),
('Joshua Thompson', 'Data Science', 'Junior', 'Member'),
('Mark Davis', 'Computer Engineering', 'Senior', 'Guest'),
('Tylin Delaney', 'Cybersecurity', 'Freshman', 'Member'),
('Kevin Brown', 'Software Engineering', 'Freshman', 'Member'),
('Sophia Martinez', 'Business Technology', 'Senior', 'Guest'),
('Andre Dumas','Information Technology', 'Post-Graduate', 'Advisor'),
('Vickie Patel', 'Data Science', 'Senior', 'Member'),
('Jillian Williams', 'Information Technology', 'Senior', 'Guest'),
('Jordan Rivers', 'Data Science', 'Junior', 'Member'),
('Kristine Martin', 'Electrical Engineering', 'Freshman', 'Member'),
('Sheri Hall', 'Information Technology', 'Post-Graduate', 'Guest'),
('Kevin Jordan', 'Mechanical Engineering', 'Freshman', 'Member'),
('Corey Baker', 'Data Science', 'Sophomore', 'Member'),
('Joel Humphrey', 'Cybersecurity', 'Freshman', 'Guest'),
('Joshua Larson', 'Electrical Engineering', 'Post-Graduate', 'Member'),
('Robert Juarez', 'Computer Engineering', 'Freshman', 'Guest'),
('Deanna Garcia', 'Computer Science', 'Senior', 'Guest'),
('Kayla King', 'Electrical Engineering', 'Sophomore', 'Member'),
('Joseph Wilson', 'Computer Science', 'Junior', 'Guest'),
('Colleen Holmes', 'Computer Science', 'Post-Graduate', 'Member'),
('Shawn Rodriguez', 'Cybersecurity', 'Senior', 'Member'),
('Natalie Oconnell', 'Software Engineering', 'Freshman', 'Member'),
('Nicholas Taylor', 'Computer Science', 'Senior', 'Guest'),
('Vincent Harrington', 'Information Technology', 'Senior', 'Member'),
('Jack Christian', 'Software Engineering', 'Post-Graduate', 'Guest'),
('Doris Wallace', 'Mechanical Engineering', 'Freshman', 'Guest'),
('Victoria Gonzalez', 'Computer Science', 'Senior', 'Guest'),
('Joseph Hendrix', 'Business Technology', 'Freshman', 'Member'),
('William Mathews', 'Computer Science', 'Post-Graduate', 'Member'),
('Jeffrey White', 'Business Technology', 'Post-Graduate', 'Member'),
('Kevin Perez', 'Electrical Engineering', 'Sophomore', 'Member'),
('Kimberly Rosario', 'Cybersecurity', 'Junior', 'Guest'),
('Carol Townsend', 'Electrical Engineering', 'Junior', 'Guest'),
('William Cunningham', 'Information Technology', 'Post-Graduate', 'Guest'),
('Damon Hernandez', 'Electrical Engineering', 'Junior', 'Guest'),
('Alexandria Anderson', 'Mechanical Engineering', 'Freshman', 'Member'),
('Mark Young', 'Software Engineering', 'Senior', 'Member'),
('Jennifer Flores', 'Business Technology', 'Junior', 'Member'),
('Maurice Pearson', 'Business Technology', 'Sophomore', 'Member'),
('Patricia Palmer', 'Software Engineering', 'Post-Graduate', 'Guest'),
('Brian Hill', 'Computer Science', 'Freshman', 'Member'),
('Leslie Edwards', 'Cybersecurity', 'Junior', 'Guest'),
('Sarah Graham', 'Information Systems', 'Post-Graduate', 'Guest'),
('Brandon Flores', 'Information Technology', 'Sophomore', 'Member'),
('Terri Blake', 'Data Science', 'Post-Graduate', 'Guest'),
('Kenneth Johnson', 'Information Technology', 'Senior', 'Member'),
('Sara Haynes', 'Business Technology', 'Freshman', 'Guest'),
('Crystal Jacobs', 'Information Technology', 'Post-Graduate', 'Guest'),
('Trez Cooke', 'Mechanical Engineering', 'Sophomore', 'Member'),
('Leah Henderson', 'Computer Science', 'Junior', 'Member'),
('Andrew Gonzales', 'Cybersecurity', 'Sophomore', 'Guest'),
('Catherine Porter', 'Mechanical Engineering', 'Sophomore', 'Guest'),
('Tracy Stokes', 'Software Engineering', 'Senior', 'Member'),
('Robert Lopez', 'Mechanical Engineering', 'Sophomore', 'Guest'),
('Denise Cook', 'Business Technology', 'Post-Graduate', 'Member'),
('Sylvia Bryant', 'Business Technology', 'Freshman', 'Member'),
('Chon Martinez', 'Mechanical Engineering', 'Sophomore', 'Guest'),
('Darlene Thompson', 'Computer Science', 'Junior', 'Member'),
('Michael Anderson', 'Electrical Engineering', 'Junior', 'Member'),
('Stephanie Sanchez', 'Computer Engineering', 'Senior', 'Member'),
('Cody Nguyen', 'Data Science', 'Senior', 'Guest'),
('Sarah Tran', 'Cybersecurity', 'Freshman', 'Guest'),
('Robert Cox', 'Computer Engineering', 'Senior', 'Guest'),
('Krystal Curry', 'Cybersecurity', 'Junior', 'Guest'),
('Kelly Castillo', 'Cybersecurity', 'Junior', 'Member'),
('Becca Ramos', 'Information Technology', 'Senior', 'Guest');


-- events
INSERT INTO events (event_name, event_date) VALUES
('Semester Kickoff Game Night', '2025-02-25'),
('Tech Talk w/ Andre Dumas', '2025-11-01'),
('Resume Builder', '2025-01-16'),
('Career Workshop', '2025-09-25'),
('Study Hall', '2024-11-10'),
('EOY Project Showcase', '2025-05-01'),
('Study Hall', '2024-03-03'),
('Python Workshop', '2025-04-10');


-- event participation by students (many to many)

INSERT INTO event_participation (student_id, event_id) VALUES
(1, 1), (1, 3), (1, 5), (1, 8),
(2, 6), (3, 3), (3, 8), (3, 4), (3, 7),
(4, 5), (4, 3), (4, 7),
(5, 1), (5, 3),
(6, 8), (6, 4),
(7, 4), (7, 3),
(8, 7), (8, 6),
(9, 7), (9, 6),
(10, 6), (10, 1), (10, 8), (10, 3),
(11, 3), (11, 5), (11, 6), (11, 2),
(12, 2), (12, 5), (12, 1), (12, 6),
(13, 6), (13, 5), (13, 3),
(14, 2), (14, 6),
(15, 8), (15, 2), (15, 3), (15, 6),
(16, 5), (16, 6), (16, 8), (16, 2),
(17, 1), (17, 6), (17, 8), (17, 5),
(18, 7), (19, 6), (20, 1),
(21, 6), (21, 3), (21, 1),
(22, 8), (23, 3), (23, 7), (23, 1),
(24, 6), (24, 1), (25, 2),
(25, 5), (26, 6), (27, 5),
(27, 2), (27, 4), (27, 3);




